### ISSUE TITLE
deprecated option `object_id

### ISSUE THREAD

**Issue by aperezva** [pergolafabio/Hikvision-Addons#278]
### What happened?

The configuration for entity text.portero_entrada_isapi_request uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_isapi_request"` option with `"default_entity_id": "text.portero_entrada_isapi_request"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4

### Add-on

Hikvision Doorbell

### What version of the add-on are you running?

3.0.22

### Installation type

Home Assistant add-on

### Relevant log output

```Text
The configuration for entity sensor.portero_entrada_call_state uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_call_state"` option with `"default_entity_id": "sensor.portero_entrada_call_state"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4

The configuration for entity switch.portero_entrada_door_relay_0 uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_door_relay_0"` option with `"default_entity_id": "switch.portero_entrada_door_relay_0"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
The configuration for entity switch.portero_entrada_door_relay_1 uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_door_relay_1"` option with `"default_entity_id": "switch.portero_entrada_door_relay_1"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
The configuration for entity text.portero_entrada_isapi_request uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_isapi_request"` option with `"default_entity_id": "text.portero_entrada_isapi_request"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
```

### Relevant configuration

```YAML

```

**Comment by pergolafabio** [comment]
Ok, will have a look next week

**Comment by pergolafabio** [comment]
fixed in v24

**Comment by aperezva** [comment]
Remain the same problem and now it s not working 2025-10-07 15:34:16.538 | ERROR    | __main__:main:25 - Configuration error: This addon needs the Mosquitto broker to work correctly. Please see the Documentation tab for details.
2025-10-07 15:34:17.481 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2025-10-07 15:34:17.481 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2025-10-07 15:34:17.484 | ERROR    | config:mqtt_config_from_supervisor:40 - MQTT service not available
2025-10-07 15:34:17.484 | ERROR    | __main__:main:25 - Configuration error: This addon needs the Mosquitto broker to work correctly. Please see the Documentation tab for details.
2025-10-07 15:34:54.512 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2025-10-07 15:34:54.512 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2025-10-07 15:34:54.515 | ERROR    | config:mqtt_config_from_supervisor:40 - MQTT service not available
2025-10-07 15:34:54.515 | ERROR    | __main__:main:25 - Configuration error: This addon needs the Mosquitto broker to work correctly. Please see the Documentation tab for details.
2025-10-07 15:37:23.656 | DEBUG    | config:load_mqtt_config:129 - Loading MQTT configuration from supervisor
2025-10-07 15:37:23.656 | DEBUG    | config:mqtt_config_from_supervisor:36 - Requesting MQTT service configuration to supervisor
2025-10-07 15:37:23.658 | ERROR    | config:mqtt_config_from_supervisor:40 - MQTT service not available
2025-10-07 15:37:23.658 | ERROR    | __main__:main:25 - Configuration error: This addon needs the Mosquitto broker to work correctly. Please see the Documentation tab for details.

**Comment by pergolafabio** [comment]
That's something else, you are missing the MQTT data, of you use local broker, remove the MQTT broker, it should detect it itself

**Comment by aperezva** [comment]
fixed this problem but, I still hacve the other warninng

The configuration for entity sensor.portero_entrada_call_state uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_call_state"` option with `"default_entity_id": "sensor.portero_entrada_call_state"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
The configuration for entity switch.zigbee2mqtt_bridge_permit_join uses the deprecated option `object_id` to set the default entity id. 
The configuration for entity switch.portero_entrada_door_relay_0 uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_door_relay_0"` option with `"default_entity_id": "switch.portero_entrada_door_relay_0"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
The configuration for entity switch.portero_entrada_door_relay_1 uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_door_relay_1"` option with `"default_entity_id": "switch.portero_entrada_door_relay_1"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4
The configuration for entity text.portero_entrada_isapi_request uses the deprecated option `object_id` to set the default entity id. Replace the `"object_id": "portero_entrada_isapi_request"` option with `"default_entity_id": "text.portero_entrada_isapi_request"` in your published discovery configuration to fix this issue, or contact the maintainer of the integration that published this config to fix this. This will stop working in Home Assistant Core 2026.4

**Comment by aperezva** [comment]
It´s appear when I reboot home assistant

**Comment by pergolafabio** [comment]
Are you sure you are running the addon, restart HA ? Still see the error? In my case it's gone

**Comment by aperezva** [comment]
Now it´s ok, it was strange after update ii lost my mqtt configuration, but after apgrade and config again mqtt, now it s fiexd

Thanks a lot for your time, Without people like you it would be impossible
